<?php
/**
* @file
* Module file for Curricular Module Handling */
/**
* Implements of hook_init(). */
function curricular_module_handling_init() {
	drupal_set_message('Curricular modules are alive!');
}

/**
* Implements hook_menu()
*/
function curricular_module_handling_menu(){
	
	$items = array();
	  $items['admin/curricular_module_versioning'] = array(
	      'title' => 'Curricular Module Versioning',
	      'description' => 'My Description',
	      'position' => 'left',
	      'weight' => -100,
	      'page callback' => 'system_admin_menu_block_page',
	      'access arguments' => array('administer site configuration'),
	      'file' => 'system.admin.inc',
	      'file path' => drupal_get_path('module', 'system'),
	  );
	  //We need at least one child item, otherwise parent will not show up
	  
	  $items['admin/curricular_module_versioning/verify_module'] = array(
	      'title' => 'Verify Update',
	      'description' => 'My Description',
	      'page callback' => 'verify_module_renderable_page',
	      'page arguments' => array('my-path'),
	      'access arguments' => array('administer site configuration'),
	  );
	
	$items['curricular_module_handling/custom'] = array(
	    'title' => 'Custom page',
	    'page callback' => 'curricular_module_handling_custom',
	    'access arguments' => array('access content'),
	  );
 
	return $items;
}

/**
* Implements hook_theme()
*/
function curricular_module_handling_theme($existing, $type, $theme, $path) {
  return array(
    'curricular_module_handling_function' => array(
      'variables' => array('forums' => NULL, 'topics' => NULL),
    ),
    'verify_module_template' => array(
      'variables' => array('text_one' => NULL),
	  'template' => 'verify_module_template',
    ),
  );
}
/**
* Custom callback function - verify module template
*/
function verify_module_renderable_page(){
	$text_one = 'Yeahyeahyeah';
	$output = array(
		'#theme' => 'verify_module_template',
		'#type' => 'markup',
		'#text_one' => $text_one,
	);
	return $output;
}
/**
* Implement drupal_set_message().
*/
function curricular_module_handling_set_message($msg){
	drupal_set_message($msg);
	return;
}
/**
* Implements hook_submit().
*/
function curricular_modules_node_form_submit($form_id, &$form_state) {

		$title = $form_state['values']['title'];
		db_insert('curricular_modules')
		    ->fields(array(
		      'title' => $title,
		    ))
		    ->execute();
  // To make your code easier to read, save the data from $form_state into your own variables.
 /* $name     = $form_state['values']['name'];  // I assume the name of the field is 'name'.
  $position = $form_state['values']['position']; // I assume the name of the field is 'position'.
  $salary   = $form_state['values']['salary']; // etc.
  $age      = $form_state['values']['age'];

  // Write the SQL query, using %s and %d as placeholders for the data that you're going to add. (See below.)
  $sql_query = "INSERT INTO {employees} ('name','position','salary','age') VALUES ('%s', '%s', '%s', %d)";

  // Save the data to the database, using $success to check for errors. (See below.)
  if ($success = db_query($sql_query,$name,$position,$salary,$age)) {
    // Tell the user that the employee has been saved.
    drupal_set_message($name . t(' has been saved.'));
  }
  else { // If there's an error, $success will evaluate to FALSE, and the following code will execute.
    drupal_set_message(t('There was an error saving your data. Please try again.'));
  }
*/
}